### ISSUE TITLE
Docker container crashes with error message "AttributeError: 'NoneType' object has no attribute 'setdefault'"

### ISSUE THREAD

**Issue by Huddeij** [clemcer/loggifly#11]
Docker container crashes with this error message:
docker logs:
```
loggifly  | 2025-03-29 12:52:08,013 - INFO - Loggifly started
loggifly  | 2025-03-29 12:52:08,013 - INFO - config.yaml succesfully loaded.
loggifly  | Traceback (most recent call last):
loggifly  |   File "/app/app.py", line 27, in <module>
loggifly  |     config = load_config()
loggifly  |              ^^^^^^^^^^^^^
loggifly  |   File "/app/load_config.py", line 201, in load_config
loggifly  |     yaml_config.setdefault(key, {})
loggifly  |     ^^^^^^^^^^^^^^^^^^^^^^
loggifly  | AttributeError: 'NoneType' object has no attribute 'setdefault'
loggifly exited with code 1
```

compose.yml:
```
services:
  logsend:
    image: ghcr.io/clemcer/loggifly:latest
    container_name: loggifly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logsend/config.yaml:/app/config.yaml
    environment:
      - TZ=Europe/Berlin
      - NTFY_URL="https://ntfy.example.de"
      - NTFY_TOPIC="docker_logs"
      - NTFY_USERNAME=${NTFY_USER}
      - NTFY_PASSWORD=${NTFY_PASSWORD}
      - CONTGAINERS="<list of containers>"
    restart: unless-stopped
```

./logsend/config.yaml exists but is empty.

System:
Proxmox LXC on a AMD Ryzen 5 System
LXC is running Alpine Linux v3.21
