### ISSUE TITLE
Request notification_title:

### ISSUE THREAD

**Issue by ahmaddxb** [clemcer/loggifly#20]
Have the notification_title per keyword and regex

**Comment by clemcer** [comment]
could you elaborate what you mean by that?
Do you want to separately set keywords and regex patterns in `notification_title` instead of keywords and regex patterns being combined in the `keywords` variable?

**Comment by ahmaddxb** [comment]
```
    traefik:
      ntfy_tags: closed_lock_with_key
      ntfy_priority: 3
      ntfy_topic: security
      attachment_lines: 50
      notification_cooldown: 2
      notification_title: "{container}"  # Notification title if not specified per keyword
      keywords:
        # - ERR
        - regex: "(?P<timestamp>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+\\d{2}:\\d{2}) ERR EntryPoint doesn't exist entryPointName=(?P<entrypoint>[\\w-]+) routerName=(?P<router>[\\w@-]+)"
          notification_title: "{container} - EntryPoint Error"
          template: "​\n❗ Missing EntryPoint Detected!\n📛 EntryPoint: {entrypoint}\n🚦 Router: {router}\n🕐 {timestamp}"
          hide_pattern_in_title: true
        - regex: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+\d{2}:\d{2}) WRN A new release of Traefik has been found: (?P<version>\d+\.\d+\.\d+)\. Please consider updating\.'
          template: "​\n🚀 New Traefik release available!\n🔢 Version: {version}\n🕐 {timestamp}"
          notification_title: "{container} - Update Available"
          hide_pattern_in_title: true
```
