### ISSUE TITLE
Deactivate Startup/Shutdown Notifications

### ISSUE THREAD

**Issue by iLuckyW** [clemcer/loggifly#28]
Would it be possible to add an environment variable to disable these notifications? Especially in docker swarm it can be a little bit annoying to get a notification for each node.

**Comment by iLuckyW** [comment]
Oh, I overread this in the README. But I have noticed something else, when using the example docker swarm config.yaml the container fails with this error:

CRITICAL - Error loading Config: Field '': Value error, No keywords configured. You have to set keywords either per container or globally.

**Comment by iLuckyW** [comment]
This is my compose file:
```
version: "3.8"
services:
  loggifly:
    image: ghcr.io/clemcer/loggifly:v1.3.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      LOGGIFLY_MODE: swarm
      NTFY_URL: https://ntfy.example.com
      NTFY_TOPIC: homelab
      NTFY_TAGS: ''
      NTFY_TOKEN: ${NTFY_TOKEN}
      DISABLE_SHUTDOWN_MESSAGE: 'true'
    configs:
      - source: loggifly-config
        target: /config/config.yaml  
    deploy:
      mode: global
configs:
  loggifly-config:
    external: true
```

And this the config:
```
swarm_services:
  mediastack_jellyfin:
    keywords:
      - authentication
  vaultwarden_vaultwarden:
    keywords:
      - fail
```

I also tried mounting the file directly without using docker config, but same result. This is the entire log:
```
2025-05-31 19:03:29,999 - INFO - Trying path: /config/config.yaml
2025-05-31 19:03:29,999 - INFO - The config.yaml file was found in /config/config.yaml.
2025-05-31 19:03:29,999 - CRITICAL - Error loading Config: Field '': Value error, No keywords configured. You have to set keywords either per container or globally.
2025-05-31 19:03:29,999 - INFO - Waiting 15s to prevent restart loop...
```
