### ISSUE TITLE
Receiving ntfy error when container is trying to send a message

### ISSUE THREAD

**Issue by feerlessleadr** [clemcer/loggifly#3]
Hi - just spun up this tool based on the reddit post, but am receiving an error when it tries to send a ntfy notification:

`ERROR - Error while trying to send ntfy-notification: {"code":40007,"http":400,"error":"invalid priority parameter","link":"https://ntfy.sh/docs/publish/#message-priority"}`

Here is my compose file:

```
services:
  loggifly:
    image: ghcr.io/clemcer/loggifly:latest
    container_name: loggifly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #      - ./config.yaml:/app/config.yaml  # Path to your config file (ignore if you are only using environment variables)
    environment:
      # Choose at least one notification service
      NTFY_URL: https://ntfy.mydomain.com # or your self-hosted instance
      NTFY_TOPIC: docker-alerts # e.g., "docker_alerts"
      # Token or Username+Password In case you need authentication
      NTFY_TOKEN: MYTOKEN
      # NTFY_USERNAME:
      # NTFY_PASSWORD:
      # APPRISE_URL: "discord://..."      # Apprise-compatible URL

      CONTAINERS: apprise-api,audiobookshelf-audiobookshelf-1,bazarr,bookstack,bookstack_db,ddns-updater,dockge-dockge-1,dozzle,immich_machine_learning,immich_postgres,immich_redis,immich_server,iptvboss-iptvboss-1,jellyseerr,memos,ntfy,nzbhydra2,olivetin,paperless-broker-1,paperless-db-1,paperless-gotenberg-1,paperless-tika-1,paperless-webserver-1,picard-picard-1,pinchflat-pinchflat-1,pingvin-pingvin-share-1,radarr,recyclarr,sonarr,tubetube,uptime-kuma,vaultwarden,watchtower-watchtower-1 # Comma-separated list
      GLOBAL_KEYWORDS: error,failed login,password # Basic keyword monitoring
      GLOBAL_KEYWORDS_WITH_ATTACHMENT: critical # Attaches a log file to the notification
    restart: unless-stopped
networks: {}

```
