### ISSUE TITLE
[Feature Request] Configure through docker labels

### ISSUE THREAD

**Issue by iLuckyW** [clemcer/loggifly#30]
I would really appreciate the option to configure logging rules using docker labels directly at the services.

```
services:
  webserver:
    image: nginx
    labels:
      loggifly.keywords[0].regex: Error
      loggifly.keywords[0].template: Error happend
      loggifly.keywords[1].regex: Access
      loggifly.keywords[1].template: Access occurred
```

For swarm mode the labels then would be under 

```
services:
  webserver:
    image: nginx
    deploy:
      labels:
        ...
```

This would allow having the log config directly at the service and would make it easier to maintain in my opinion. Maybe there is a better way to allow for multiple regex to be defined, this is just what I saw being used in other projects.
